---
- apt: update_cache=yes cache_valid_time=3600
  name: Run the equivalent of "apt-get update" as a separate step
- apt: upgrade=dist autoremove=true
  name: Update all packages to the latest version
- name: Install apt packages defined in apt_pkgs
  apt: name={{item}} state=installed
  when: apt_pkgs is defined
  with_items:
    - "{{apt_pkgs}}"
