---
- debug:
    var: 'hostvars[inventory_hostname]'
    verbosity: 4
  name: Display all variables/facts known for a host
- git: repo=ssh://git@github.com/oalders/dot-files.git dest=~/dot-files accept_hostkey=yes recursive=yes track_submodules=no force=yes
  name: check out dot files from github
  when: ansible_nodename != 'vagrant'
- args:
    chdir: '{{user_home}}/dot-files'
  command: /bin/bash install.sh -s
  environment:
    GOPATH: '{{user_home}}/go'
  name: Install dot files
  when: ansible_nodename != 'vagrant'
