---
- debug:
    var: "hostvars[inventory_hostname]"
    verbosity: 4
  name: Display all variables/facts known for a host
- apt:
    pkg:
      - cpanminus
      - libssl-dev
      - python3-pip
- git:
    repo: https://github.com/oalders/dot-files.git
    dest: "/home/{{user}}/dot-files"
    accept_hostkey: true
    recursive: true
    track_submodules: false
    force: true
  name: "Check out dot files from github for {{user}}"
  when: ansible_nodename != 'vagrant'
  become_user: "{{user}}"
- args:
    chdir: "/home/{{user}}/dot-files"
  command: /bin/bash install.sh -s
  environment:
    GOPATH: "/home/{{user}}/go"
  name: "Install dot files for {{item}}"
  when: ansible_nodename != 'vagrant'
  become_user: "{{user}}"
