---
- git: repo=https://github.com/oalders/dot-files.git dest=/home/{{item}}/dot-files accept_hostkey=yes recursive=yes track_submodules=no force=yes
  name: "Check out dot files from github for {{item}}"
  when: ansible_nodename != 'vagrant'
  become_user: "{{item}}"
- args:
    chdir: '/home/{{item}}/dot-files'
  command: /bin/bash install.sh -s
  environment:
    GOPATH: '/home/{{item}}/go'
  name: "Install dot files for {{item}}"
  when: ansible_nodename != 'vagrant'
  become_user: "{{item}}"
