---
- mysql_db:
    name: "{{item.name}}"
    login_user: "{{item.login_user}}"
    login_password: "{{item.login_password}}"
    state: dump
    target: "/tmp/{{item.name}}-{{ ansible_date_time.iso8601 }}.sql"
  name: Dump database to /tmp
