---
- name: adds {{ app_id }}.service files
  template:
    src: starman-service.j2
    dest: "/etc/systemd/system/{{ app_id }}.service"
- name: Reload app
  systemd: 'name={{app_id}} daemon_reload=yes state=restarted enabled=yes'
