---
- name: "Maybe add {{app.app_id}}.service files"
  template:
    dest: '/etc/systemd/system/{{ app.app_id }}.service'
    src: starman-service.j2
  when: app.starman is defined
- name: Maybe reload {{app.app_id}}
  systemd: 'name={{app.app_id}} daemon_reload=true state=restarted enabled=true'
  when: app.starman is defined
