---
- name: 'adds {{ app_id }}.service files'
  template:
    dest: '/etc/systemd/system/{{ app_id }}.service'
    src: starman-service.j2
- name: Reload app
  systemd: 'name={{app_id}} daemon_reload=yes state=restarted enabled=yes'
