---
- name: Maybe create group
  group:
    name: '{{app_user}}'
    state: present
- name: Maybe create user and home dir
  user:
    createhome: yes
    group: '{{app_user}}'
    home: '{{user_home}}'
    name: '{{app_user}}'
    shell: /bin/bash
