---
- group:
    name: "{{admin_user}}"
    state: present
  name: Maybe create group
- name: "Maybe create user {{admin_user}} with home dir {{user_home}}"
  user:
    createhome: true
    group: "{{admin_user}}"
    home: "{{user_home}}"
    name: "{{admin_user}}"
    shell: /bin/bash
