---
- name: "Install some default apt packages"
  apt:
    name: "{{ packages }}"
    force_apt_get: true
  vars:
    packages:
      - curl
      - git
      - golang
      - lynx
      - ncdu
      - nmap
      - npm
      - ntp
      - perltidy
      - ruby
      - tig
      - tree
      - unzip
- include_role:
    name: oefenweb.updatedb
