---
- apt: 'name={{item}} state=present'
  name: Install list of packages
  with_items:
    - curl
    - git
    - golang
    - lynx
    - ncdu
    - npm
    - ntp
    - perltidy
    - ruby2.3
    - tig
    - tree
    - unzip
- include_role:
    name: tersmitten.updatedb
