---
- file:
    path: '{{app.log_dir}}'
    state: directory
  become_user: "{{app.owner}}"
  name: 'Create log directory at {{app.log_dir}}'
- file:
    path: '{{app.pid_dir}}'
    state: directory
  name: 'Create pid directory at {{app.pid_dir}}'
  become_user: "{{app.owner}}"
