---
- file:
    path: '{{app.log_dir | default(app.checkout_root + "/var/log")}}'
    state: directory
  become_user: "{{app.owner}}"
  name: 'Maybe create log directory for {{app.app_id}}'
- file:
    path: '{{app.pid_dir | default(app.checkout_root + "/var/pid")}}'
    state: directory
  name: 'Maybe create pid directory for {{app.app_id}}'
  become_user: "{{app.owner}}"
