---
- apt:
    pkg:
      - cpanminus
    state: present
  become: true
  name: "Install cpanminus from apt"
- cpanm:
    name: "{{item}}"
  with_items:
    - Carton
    - App::cpm
- include_tasks: tasks.yml
  loop_control:
    loop_var: app
  with_items: "{{apps}}"
