---
- apt:
    pkg:
      - cpanminus
    state: present
  become: true
  name: "Install cpanminus from apt"
- cpanm:
    name: "{{item}}"
  with_items:
    - Carton
    - App::cpm
- name: Copy common-cpanfile
  template:
    dest: /tmp/common-cpanfile
    mode: 0600
    src: common-cpanfile
- name: "cpm install"
  args:
    chdir: /tmp
  command:
    argv:
      - cpm
      - install
      - --global
      - --mirror
      - https://cpan.metacpan.org
      - --mirror
      - http://CPAN.mirror.rafal.ca/
      - --workers
      - "{{ansible_processor_cores}}"
      - --cpanfile
      - common-cpanfile
  environment:
    PERL5LIB: "{{user_home}}/perl5/lib/perl5"
  ignore_errors: true
- include_tasks: tasks.yml
  loop_control:
    loop_var: app
  with_items: "{{apps}}"
