---
- debug:
    msg: 'cores: {{ansible_processor_cores}}'
- apt: 'pkg={{item}} state=installed'
  become: yes
  name: 'Install {{item}} from apt'
  with_items:
    - cpanminus
- cpanm:
    name: '{{item}}'
  with_items:
    - Carton
    - App::cpm
- name: Copy common-cpanfile
  template: 'src=common-cpanfile dest="/tmp/common-cpanfile" mode=0600'
- args:
    chdir: '/tmp'
  command: 'cpm install --global --mirror https://cpan.metacpan.org --mirror http://CPAN.mirror.rafal.ca/ --workers {{ansible_processor_cores}} --cpanfile common-cpanfile'
  environment:
  ignore_errors: yes
- include: tasks.yml
  loop_control:
    loop_var: app
  with_dict: '{{apps}}'
