---
- include_role:
    name: common-roles/pubkey
- include_role:
    name: common-roles/apt
- include_role:
    name: common-roles/firewall
- include_role:
    name: common-roles/system
- include_role:
    name: common-roles/ssl-certs
- include_role:
    name: common-roles/git-checkout
- include_role:
    name: common-roles/gitignore
- include_role:
    name: common-roles/var
