---
- lineinfile:
    dest: /etc/sudoers
    line: Defaults env_keep += "SSH_AUTH_SOCK"
    regexp: SSH_AUTH_SOCK
    state: present
  name: Add ssh agent line to sudoers
- lineinfile: "dest=/etc/sudoers state=present regexp='^%{{app_user}}' line='%{{app_user}} ALL=(ALL) NOPASSWD: ALL'"
